### ISSUE TITLE
Add missing support for section

### ISSUE THREAD

**Issue by abunashir** [metanorma/coradoc#36]
### Todos

- [ ] Support for predefined titles
- [ ] Support for deviating sections titles
- [ ] Attributes with key, value pair, eg: `[heading=foreword]`
- [ ] Attributes with with multi value, eg: `[bibliography,heading=normative]`
- [ ] Support for parsing keep title: eg: `[heading=foreword,keeptitle=true]`
- [ ] Support for blank subclause heading: `=== {blank}`
- [ ] Support for inline heading: `[%inline-header]\n==== Sieve,`
- [ ] Support for variant title: `[.variant-title,type=sub]`
- [ ] Support for level attribute in heading: `[level=6]`

Reference: https://www.metanorma.org/author/topics/sections/

**Comment by abunashir** [comment]
@ronaldtse: This are the things that is still missing for the section parsing, let me know if you can think of anything else.

**Comment by opoudjis** [comment]
... There's a lot of functionality here that Metanorma, not Asciidoctor, handles, with downstream processing of Asciidoctor processing.

I continue to think that reimplementing Asciidoctor as coradoc is a wasteful idea, but reimplementing Asciidoctor PLUS Metanorma, which is what this ticket is implying, plus doing so without referring to the code, but only the user-facing documentation, is even more wasteful.

You need to focus on built-in Asciidoctor functionality, and defer Metanorma-specific functionality, if this is ever going to be done. That means that you must prioritise:

Attributes with key, value pair, eg: [heading=foreword]
Attributes with with multi value, eg: [bibliography,heading=normative]
Support for blank subclause heading: === {blank}
Support for level attribute in heading: [level=6]

Add to that support for all the predefined section types as role attributes, if you haven't already: `[abstract]`, `[bibliography]`, `[annex]`, [preface]`, `[index]`, `[acknowledgements]`. See https://docs.asciidoctor.org/asciidoc/latest/sections/styles/ , although those are the types we use.

It is way premature for you to be looking at the Metanorma ad hoc solution of keep-title, when coradoc doesn't even support parsing attributes on sections. Please focus on Asciidoctor functionality first. Metanorma ignores some of it (sectnums, sectnumlevels, sectids), but presupposes much of it. The place you should be looking is https://docs.asciidoctor.org/asciidoc/latest/sections/titles-and-levels/ and following: 

* Do you cope with document preambles (initial text without section header)?
* Do you autoassign identifiers to clauses? Metanorma overrides them with IDs if autogenerated, but it does presuppose there is something there to override.
* Do you deal with anchors?
* Do you deal with "auxiliary IDs"? (We do them as index terms and bookmarks)

**Comment by abunashir** [comment]
Hey @opoudjis, thanks a lot for your comment, and you added quite some valuable information there 🙇🏼 

I totally agree it's probably gonna be quite some work here and going through the metanorma docs might not make it any easier.

I do have little visibility on what are the things that are being used the most by the doc author.  If you would be kind enough to add those missing things for sections in priority orders (besides the one you mentioned above) would be super helpful for me. Thanks a lot in advance Nick ❤️
